name: Keep Repository Active

on:
  schedule:
    - cron: "0 0 1 * *"  # 매월 1일 00:00 UTC
  workflow_dispatch: {}

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Keep alive
        uses: gautamkrishnar/keepalive-workflow@v2
        with:
          commit_message: "Keep repository active"
          committer_username: "github-actions[bot]"
          committer_email: "github-actions[bot]@users.noreply.github.com"